---
name: 🔐 pre-commit hooks

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  release:
    types: [released]
env:
  IS_GITHUB_ACTION: 1

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
