name: 🆙 Release file check

on:
  pull_request:
    branches:
    - main
    paths:
    - "qtgql/**"
    - ".github/workflows/release_check.yml"
    - "pyproject.toml"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Check release
        id: check_release
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry githubrelease httpx==0.18.2 autopub
          echo "release=$(autopub check)" >> $GITHUB_OUTPUT

      - uses: mshick/add-pr-comment@v2
        name: add release comment
        with:
          message: |
            {{ $GITHUB_OUTPUT }}
