name: 🆙 Release file check

on:
  pull_request:
    branches:
    - main
    paths:
    - "qtgql/**"
    - ".github/workflows/release_check.yml"
    - "pyproject.toml"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    if: ${{ github.ref=='refs/heads/main'}}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Check release
        id: check_release
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry githubrelease httpx==0.18.2 autopub
          echo "release=$(autopub check)" >> $GITHUB_OUTPUT

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
